'use client';

import type { Metadata } from 'next';
import { Inter } from 'next/font/google';
import { usePathname } from 'next/navigation';

import './globals.css';
import styles from '../styles/layout/layout.module.css';
import Header from '@/components/layout/header';
import Footer from '@/components/layout/footer';
import Sidebar from '@/components/layout/sidebar';
import ToastProvider from '@/components/ToastProvider';

const inter = Inter({ subsets: ['latin'] });

// export const metadata: Metadata = {
//     title: 'Create Next App',
//     description: 'Generated by create next app',
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const pathName = usePathname();
  const isNotificationPage = pathName === '/me/notification';

  return (
    <html lang="en">
      <body className={inter.className + ' ' + styles['wrapper']}>
        <Header />
        <div className={styles['body']}>
          {!isNotificationPage && <Sidebar />}
          <div className={styles['content']}>
            <ToastProvider>{children}</ToastProvider>
          </div>
        </div>

        <Footer />
      </body>
    </html>
  );
}
