import type { Metadata } from 'next';
import { Inter } from 'next/font/google';

import styles from '@/styles/layout/layout.module.css';
import Header from '@/components/layout/Header/header';
import Footer from '@/components/layout/footer';
import Sidebar from '@/components/layout/sidebar';
import { currentUserId } from '@/lib/auth';
import { getUserById } from '@/data/user';
import { getUserCourses } from '@/actions/userCourse';

const inter = Inter({ subsets: ['latin'] });

export const metadata: Metadata = {
  title: 'Create Next App',
  description: 'Generated by create next app',
};

export default async function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  const userId = await currentUserId();
  let user = undefined;
  let courses = undefined;
  if (userId) {
    user = await getUserById(userId);
    courses = await getUserCourses(userId);
  }

  return (
    <div className={styles['wrapper']}>
      <Header user={user} courses={courses} />

      <div className={styles['body']}>
        <Sidebar />
        <div className={styles['content']}>{children}</div>
      </div>

      <Footer />
    </div>
  );
}
